language: node_js

node_js:
  - "6.11"

services:
  - mysql

env:
  NODE_ENV=travis

before_script:
  - ls -lah
  - mysql -e 'CREATE DATABASE co_mysql_test;'
  - mysql co_mysql_test < ./init.sql/01-tables.sql
  - npm install

script:
  - npm test

notifications:
  email: false
