version: '2'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=co_mysql_test"
      - "MYSQL_USER=co_mysql_test"
      - "MYSQL_PASSWORD=co_mysql_test"
      - "TZ=Asia/Tokyo"
    command: >
      mysqld
        --character-set-server=utf8
        --collation-server=utf8_unicode_ci
        --skip-character-set-client-handshake
        --explicit_defaults_for_timestamp=1
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  node:
    image: node:boron-alpine
    container_name: node
    hostname: node
    volumes:
      - ".:/app"
    working_dir: /app
    command: [sh, -c, npm install --no-bin-links]
    depends_on:
      - mysql
